# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1427928297);
user_pref("app.update.lastUpdateTime.background-update-timer", 1423427213);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1423427093);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1427927967);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1427928087);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.parent_directory", "C:\\Users\\powelm6\\Desktop\\WADServer2015\\core\\palemoon\\User\\Palemoon\\Profiles\\Default");
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.lastDir", "C:\\Users\\powelm6\\Desktop\\WADServer2015\\core\\palemoon\\Downloads");
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 3132);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20141021154431");
user_pref("browser.startup.homepage_override.mstone", "25.0.0");
user_pref("browser.startup.page", 0);
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("extensions.blocklist.pingCountTotal", 4);
user_pref("extensions.blocklist.pingCountVersion", 4);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:25.0.2");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Users\\\\powelm6\\\\Desktop\\\\WADServer2015\\\\core\\\\palemoon\\\\Bin\\\\Palemoon\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1414052667081,\"rdfTime\":1413907774000}}}]");
user_pref("extensions.lastAppVersion", "25.0.2");
user_pref("extensions.lastPlatformVersion", "25.0.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20141021154431");
user_pref("gecko.mstone", "25.0.0");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("intl.charsetmenu.browser.cache", "UTF-8, windows-1252");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.autoconfig_url", "file:///C:/Users/powelm6/Desktop/WADServer2015/home/us_pac/proxy.pac");
user_pref("network.proxy.type", 2);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.importedState", true);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("status4evar.firstRun", false);
user_pref("status4evar.migration", 6);
user_pref("toolkit.startup.last_success", 1427928176);
user_pref("toolkit.telemetry.previousBuildID", "20141021154431");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
